### ISSUE TITLE
Identify function

### ISSUE THREAD

**Issue by enridestroy** [Stovent/StreamGen_cpp#1]
I do not think that Identify should only check support of (immediate) subsets. I think it should also check if immediate subsets are generators or not (i.e. Theorem 2).

**Comment by enridestroy** [comment]
This is the tricky part since it is not in the paper ^^

**Comment by Stovent** [comment]
Definition 1, 2 and 3 says the status of a node is only based on its support and on the support of its subsets, I don't see why the subsets node type should be taken in consideration.

**Comment by enridestroy** [comment]
I am not saying that it is "false".  I say that in my interpretation of their work Theorem 2 should be used instead of definition 2

**Comment by enridestroy** [comment]
Otherwise, Theorem 2 is useless ^^

**Comment by enridestroy** [comment]
The definition 2 says that if an itemset has no other subset of same support then it is 100% a generator

**Comment by enridestroy** [comment]
Theorem 2 says that a generator has all its subsets as generators. It does NOT says that if all its subsets are generators it is a generator.

**Comment by enridestroy** [comment]
If you can find an immediate subset that is not a generator then it cannot be a generator. If all its subsets are generators, then you still need to check if one has same support. The difference is that in one case you need to check all (immediate) subsets and the other only generator (immediate) subsets (faster)

**Comment by Stovent** [comment]
OK I see. I did not thought of it this way, and it may be faster indeed
