### ISSUE TITLE
tidlist is not correct here

### ISSUE THREAD

**Issue by enridestroy** [Stovent/StreamGen_cpp#5]
https://github.com/Stovent/StreamGen_cpp/blob/4d69561ae7ca4822fe59b36c8849a4dd0d07b613/StreamGen_cpp/StreamGen.cpp#L88

**Comment by enridestroy** [comment]
I think it should be inter(node->tidlist, item->tidlist)

**Comment by Stovent** [comment]
yeah I did not took the time to think of it.
I think it should be inter(node->tidlist, child.second->tidlist)

**Comment by enridestroy** [comment]
Same result, should be also ok I think
